In [1]:
import pandas as pd

In [30]:
dataset=pd.read_csv("kd.csv")

In [31]:
dataset.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [4]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

## For null values ; action to be taken
# 1)Replace all null values by central tendency 
# 2)Delete entire row
# 3)respective to the problem, replace the missing value
# 4) consider this as a semi supervised model, create a model, so that we can predict the missing value

In [5]:
import sys
import os
path = os.path.abspath(r'D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing')
sys.path.append(path)
print(f"Checking path: {path}")
print(f"File exists: {os.path.exists(os.path.join(path, 'univariate.py'))}")

from univariate import univariate
obj=univariate()
quan,qual = obj.quanQual(dataset)

Checking path: D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing
File exists: True

In [6]:
quan

['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [7]:
qual

['rbc',
 'pc',
 'pcc',
 'ba',
 'pcv',
 'wc',
 'rc',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [8]:
dataset[qual].head()

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,NaN,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,NaN,normal,notpresent,notpresent,38,6000,NaN,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd

In [9]:
import numpy as np
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan, strategy="most_frequent") # Imputer filling null values with Mean(CEntral TEndency)
imp.fit(dataset[qual])
df=imp.transform(dataset[qual])

In [10]:
dataset[qual].head()

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,NaN,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,NaN,normal,notpresent,notpresent,38,6000,NaN,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd

In [11]:
dataset[qual].head()

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,NaN,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,NaN,normal,notpresent,notpresent,38,6000,NaN,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd

In [12]:
df

array([['normal', 'normal', 'notpresent', ..., 'no', 'no', 'ckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'ckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'yes', 'ckd'],
       ...,
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'notckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'notckd'],
       ['normal', 'normal', 'notpresent', ..., 'no', 'no', 'notckd']],
      shape=(400, 14), dtype=object)

In [13]:
df1=pd.DataFrame(df,columns = qual)

In [14]:
df1

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,38,6000,5.2,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,5.2,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [15]:
quan

['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [16]:
import sys
import os

path = os.path.abspath(r'D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing')
sys.path.append(path)
print(f"Checking path: {path}")
print(f"File exists: {os.path.exists(os.path.join(path, 'univariate.py'))}")

from univariate import univariate
obj_qu=univariate()
descriptive=obj_qu.univariate(dataset,quan)

Checking path: D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing
File exists: True

D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:31: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Mean"]    = dataset[col_name].mean()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:32: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Median"]  = dataset[col_name].median()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Mode"]    = dataset[col_name].mode()[0]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:34: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q1:25%"]  = dataset.describe()[col_name]["25%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:35: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q2:50%"]  = dataset.describe()[col_name]["50%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:36: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q3:75%"]  = dataset.describe()[col_name]["75%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:39: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["99%"] = np.nanpercentile(dataset[col_name], 99)
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:53: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q4:100%"] = dataset.describe()[col_name]["max"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:54: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["IQR"] = descriptive[col_name]["Q3:75%"] - descriptive[col_name]["Q1:25%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:55: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["1.5rule"] = 1.5 *  descriptive[col_name]["IQR"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:56: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Lesser"] =  descriptive[col_name]["Q1:25%"] - descriptive[col_name]["1.5rule"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:57: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Greater"] = descriptive[col_name]["Q3:75%"] + descriptive[col_name]["1.5rule"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:58: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Min"] = dataset[col_name].min()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:59: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Max"] = dataset[col_name].max()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:60: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Kurtosis"] = dataset[col_name].kurtosis()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:61: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["skew"] = dataset[col_name].skew()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:62: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["MinOutlier"] = descriptive[col_name]["Min"] < descriptive[col_name]["Lesser"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:63: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["MaxOutlier"] = descriptive[col_name]["Max"] > descriptive[col_name]["Greater"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:31: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Mean"]    = dataset[col_name].mean()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:32: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Median"]  = dataset[col_name].median()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

In [17]:
descriptive

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Mean,199.5,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
Median,199.5,55.0,80.0,1.02,0.0,0.0,121.0,42.0,1.3,138.0,4.4,12.65
Mode,0,60.0,80.0,1.02,0.0,0.0,99.0,46.0,1.2,135.0,3.5,15.0
Q1:25%,99.75,42.0,70.0,1.01,0.0,0.0,99.0,27.0,0.9,135.0,3.8,10.3
Q2:50%,199.5,55.0,80.0,1.02,0.0,0.0,121.0,42.0,1.3,138.0,4.4,12.65
Q3:75%,299.25,64.5,80.0,1.02,2.0,0.0,163.0,66.0,2.8,142.0,4.9,15.0
99%,395.01,80.1,110.0,1.025,4.0,4.0,434.9,236.2,19.162,150.0,6.589,17.653
Q4:100%,399.0,90.0,180.0,1.025,5.0,5.0,490.0,391.0,76.0,163.0,47.0,17.8
IQR,199.5,22.5,10.0,0.01,2.0,0.0,64.0,39.0,1.9,7.0,1.1,4.7
1.5rule,299.25,33.75,15.0,0.015,3.0,0.0,96.0,58.5,2.85,10.5,1.65,7.05
Lesser,-199.5,8.25,55.0,0.995,-3.0,0.0,3.0,-31.5,-1.95,124.5,2.15,3.25
Greater,598.5,98.25,95.0,1.035,5.0,0.0,259.0,124.5,5.65,152.5,6.55,22.05
Min,0,2.0,50.0,1.005,0.0,0.0,22.0,1.5,0.4,4.5,2.5,3.1
Max,399,90.0,180.0,1.025,5.0,5.0,490.0,391.0,76.0,163.0,47.0,17.8
Kurtosis,-1.2,0.05784,8.646095,-1.144357,-0.383377,5.055348,4.225594,9.345289,79.304345,85.53437,142.505912,-0.471398
skew,0.0,-0.668259,1.605429,-0.172444,0.998157,2.464262,2.010773,2.634374,7.509538,-6.996569,11.582956,-0.335095
MinOutlier,False,True,True,False,False,False,False,False,False,True,False,True
MaxOutlier,False,False,True,False,False,True,True,True,True,True,True,False

In [18]:
#import numpy as np
#from sklearn.impute import SimpleImputer
imp_qu=SimpleImputer(missing_values=np.nan, strategy="median") # Imputer filling null values with Mean(CEntral TEndency)
imp_qu.fit(dataset[quan])
df_qu=imp_qu.transform(dataset[quan])

In [19]:
df_qu

array([[  0. ,  48. ,  80. , ..., 138. ,   4.4,  15.4],
       [  1. ,   7. ,  50. , ..., 138. ,   4.4,  11.3],
       [  2. ,  62. ,  80. , ..., 138. ,   4.4,   9.6],
       ...,
       [397. ,  12. ,  80. , ..., 137. ,   4.4,  15.8],
       [398. ,  17. ,  60. , ..., 135. ,   4.9,  14.2],
       [399. ,  58. ,  80. , ..., 141. ,   3.5,  15.8]], shape=(400, 12))

In [20]:
quan

['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [21]:
df_qu1=pd.DataFrame(df_qu,columns = quan)

In [22]:
df_qu1

        id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0.0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2  138.0  4.4  15.4
1      1.0   7.0  50.0  1.020  4.0  0.0  121.0  18.0  0.8  138.0  4.4  11.3
2      2.0  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8  138.0  4.4   9.6
3      3.0  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4.0  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4  138.0  4.4  11.6
..     ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395.0  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396.0  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397.0  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398.0  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399.0  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [23]:
imp_qu

SimpleImputer(strategy='median')

In [24]:
#from univariate import univariate1
#descriptive=univariate1(dataset,quan)

import sys
import os

path = os.path.abspath(r'D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing')
sys.path.append(path)
print(f"Checking path: {path}")
print(f"File exists: {os.path.exists(os.path.join(path, 'univariate.py'))}")

from univariate import univariate
obj_qu=univariate()
descriptive=obj_qu.univariate(dataset,quan)

Checking path: D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing
File exists: True

D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:31: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Mean"]    = dataset[col_name].mean()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:32: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Median"]  = dataset[col_name].median()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Mode"]    = dataset[col_name].mode()[0]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:34: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q1:25%"]  = dataset.describe()[col_name]["25%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:35: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q2:50%"]  = dataset.describe()[col_name]["50%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:36: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q3:75%"]  = dataset.describe()[col_name]["75%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:39: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["99%"] = np.nanpercentile(dataset[col_name], 99)
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:53: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Q4:100%"] = dataset.describe()[col_name]["max"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:54: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["IQR"] = descriptive[col_name]["Q3:75%"] - descriptive[col_name]["Q1:25%"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:55: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["1.5rule"] = 1.5 *  descriptive[col_name]["IQR"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:56: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Lesser"] =  descriptive[col_name]["Q1:25%"] - descriptive[col_name]["1.5rule"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:57: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Greater"] = descriptive[col_name]["Q3:75%"] + descriptive[col_name]["1.5rule"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:58: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Min"] = dataset[col_name].min()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:59: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Max"] = dataset[col_name].max()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:60: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Kurtosis"] = dataset[col_name].kurtosis()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:61: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["skew"] = dataset[col_name].skew()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:62: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["MinOutlier"] = descriptive[col_name]["Min"] < descriptive[col_name]["Lesser"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:63: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["MaxOutlier"] = descriptive[col_name]["Max"] > descriptive[col_name]["Greater"]
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:31: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Mean"]    = dataset[col_name].mean()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:32: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[col_name]["Median"]  = dataset[col_name].median()
D:\HOPE\AICourseTam\MachineLearning\week5\Univariate\UnivariateAnalysis\3.DataProcessing\univariate.py:33: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

In [25]:
descriptive

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Mean,199.5,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
Median,199.5,55.0,80.0,1.02,0.0,0.0,121.0,42.0,1.3,138.0,4.4,12.65
Mode,0,60.0,80.0,1.02,0.0,0.0,99.0,46.0,1.2,135.0,3.5,15.0
Q1:25%,99.75,42.0,70.0,1.01,0.0,0.0,99.0,27.0,0.9,135.0,3.8,10.3
Q2:50%,199.5,55.0,80.0,1.02,0.0,0.0,121.0,42.0,1.3,138.0,4.4,12.65
Q3:75%,299.25,64.5,80.0,1.02,2.0,0.0,163.0,66.0,2.8,142.0,4.9,15.0
99%,395.01,80.1,110.0,1.025,4.0,4.0,434.9,236.2,19.162,150.0,6.589,17.653
Q4:100%,399.0,90.0,180.0,1.025,5.0,5.0,490.0,391.0,76.0,163.0,47.0,17.8
IQR,199.5,22.5,10.0,0.01,2.0,0.0,64.0,39.0,1.9,7.0,1.1,4.7
1.5rule,299.25,33.75,15.0,0.015,3.0,0.0,96.0,58.5,2.85,10.5,1.65,7.05
Lesser,-199.5,8.25,55.0,0.995,-3.0,0.0,3.0,-31.5,-1.95,124.5,2.15,3.25
Greater,598.5,98.25,95.0,1.035,5.0,0.0,259.0,124.5,5.65,152.5,6.55,22.05
Min,0,2.0,50.0,1.005,0.0,0.0,22.0,1.5,0.4,4.5,2.5,3.1
Max,399,90.0,180.0,1.025,5.0,5.0,490.0,391.0,76.0,163.0,47.0,17.8
Kurtosis,-1.2,0.05784,8.646095,-1.144357,-0.383377,5.055348,4.225594,9.345289,79.304345,85.53437,142.505912,-0.471398
skew,0.0,-0.668259,1.605429,-0.172444,0.998157,2.464262,2.010773,2.634374,7.509538,-6.996569,11.582956,-0.335095
MinOutlier,False,True,True,False,False,False,False,False,False,True,False,True
MaxOutlier,False,False,True,False,False,True,True,True,True,True,True,False

In [26]:
lesser,greater=obj_qu.outlier_col(quan,descriptive)

['age', 'bp', 'sod', 'hemo']
['bp', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot']

In [29]:
for col_name in lesser:
    dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]

for col_name in greater:
    dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]

# for col_name in quan:
#     #dataset[col_name][dataset[col_name]=="NaN"]=descriptive[col_name]["Median"]
#     print(f"{col_name}:{np.percentile(dataset[col_name],99)}")

C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] < descriptive[col_name]["Lesser"]] = descriptive[col_name]["Lesser"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]
C:\Users\Muthu Krishnan\AppData\Local\Temp\ipykernel_41704\2449550529.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[col_name][dataset[col_name] > descriptive[col_name]["Greater"]] = descriptive[col_name]["Greater"]

In [28]:
descriptive

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo
Mean,199.5,51.483376,76.469072,1.017408,1.016949,0.450142,148.036517,57.425722,3.072454,137.528754,4.627244,12.526437
Median,199.5,55.0,80.0,1.02,0.0,0.0,121.0,42.0,1.3,138.0,4.4,12.65
Mode,0,60.0,80.0,1.02,0.0,0.0,99.0,46.0,1.2,135.0,3.5,15.0
Q1:25%,99.75,42.0,70.0,1.01,0.0,0.0,99.0,27.0,0.9,135.0,3.8,10.3
Q2:50%,199.5,55.0,80.0,1.02,0.0,0.0,121.0,42.0,1.3,138.0,4.4,12.65
Q3:75%,299.25,64.5,80.0,1.02,2.0,0.0,163.0,66.0,2.8,142.0,4.9,15.0
99%,395.01,80.1,110.0,1.025,4.0,4.0,434.9,236.2,19.162,150.0,6.589,17.653
Q4:100%,399.0,90.0,180.0,1.025,5.0,5.0,490.0,391.0,76.0,163.0,47.0,17.8
IQR,199.5,22.5,10.0,0.01,2.0,0.0,64.0,39.0,1.9,7.0,1.1,4.7
1.5rule,299.25,33.75,15.0,0.015,3.0,0.0,96.0,58.5,2.85,10.5,1.65,7.05
Lesser,-199.5,8.25,55.0,0.995,-3.0,0.0,3.0,-31.5,-1.95,124.5,2.15,3.25
Greater,598.5,98.25,95.0,1.035,5.0,0.0,259.0,124.5,5.65,152.5,6.55,22.05
Min,0,2.0,50.0,1.005,0.0,0.0,22.0,1.5,0.4,4.5,2.5,3.1
Max,399,90.0,180.0,1.025,5.0,5.0,490.0,391.0,76.0,163.0,47.0,17.8
Kurtosis,-1.2,0.05784,8.646095,-1.144357,-0.383377,5.055348,4.225594,9.345289,79.304345,85.53437,142.505912,-0.471398
skew,0.0,-0.668259,1.605429,-0.172444,0.998157,2.464262,2.010773,2.634374,7.509538,-6.996569,11.582956,-0.335095
MinOutlier,False,True,True,False,False,False,False,False,False,True,False,True
MaxOutlier,False,False,True,False,False,True,True,True,True,True,True,False